apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        command: [uid_entrypoint.sh, argocd-repo-server, --repo-cache-expiration, 1m, --redis, $(ARGOCD_REDIS_SERVICE):6379]
        env:
        - name: ARGOCD_EXEC_TIMEOUT
          value: 700s
        - name: ARGOCD_GIT_ATTEMPTS_COUNT
          value: "7"
